APS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^aps_client/', include("acquisition_server.urls")),
    url(r'^aps/', include("presentation_server.urls")),
]

presentation_server/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from presentation_server.views.AlertsCleaner import AlertsCleaner
from presentation_server.views.BlockedClientsView import BlockedClientsView
from presentation_server.views.ClientConfigurationView import ClientConfigurationView
from presentation_server.views.ClientDetailsView import ClientDetailsView
from presentation_server.views.MultipleConfigureView import MultipleConfigureView
from presentation_server.views.IndexView import IndexView
from presentation_server.views.MultipleConfigureListView import MultipleConfigureListView
from presentation_server.views.PendingClientsView import PendingClientsView
from presentation_server.views.ThresholdConfigurationView import ThresholdConfigurationView
from presentation_server.views.UpdateCharts import UpdateCharts

app_name = 'aps'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^ClientConfiguration/(?P<client_pk>[0-9]+)/(?P<error_message>.*)?$',
        ClientConfigurationView.as_view(), name='ClientConfiguration'),
    url(r'^ClientDetails/(?P<client_pk>[0-9]+)$',
        ClientDetailsView.as_view(), name='ClientDetails'),
    url(r'^PendingClients/$', PendingClientsView.as_view(), name='PendingClients'),
    url(r'^BlockedClients/$', BlockedClientsView.as_view(), name='BlockedClients'),
    url(r'^UpdateCharts/$', UpdateCharts.as_view(),
        name='UpdateCharts'),
    url(r'^login/', auth_views.login,
        {
            'template_name': "presentation_server/auth/login.html",
        },
        name="login",
        ),
    url(r'^logout/', auth_views.logout,
        {
            'next_page': "/aps/",
        },
        name="logout",
        ),
    url(r'^ThresholdConfiguration$',
        ThresholdConfigurationView.as_view(), name='ThresholdConfiguration'),
    url(r'^AlertsCleaner/(?P<client_pk>[0-9]+)$',
        AlertsCleaner.as_view(), name='AlertsCleaner'),
    url(r'^MultipleConfigureList',
        MultipleConfigureListView.as_view(), name='MultipleConfigureList'),
    url(r'^MultipleConfigure',
        MultipleConfigureView.as_view(), name='MultipleConfigure'),

]

presentation_server/views/AlertsCleaner.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import View

from common.libs import AlertManager


class AlertsCleaner(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def post(self, request, *args, **kwargs):
        client_pk = kwargs["client_pk"]
        if request.POST.get('delete_single'):
            AlertManager.delete_alert(int(request.POST.get("alert_pk")))
        if request.POST.get('delete_all'):
            AlertManager.delete_all_for_client(client_pk)
        return HttpResponseRedirect(
            "{}#alerts".format(reverse("aps:ClientDetails", kwargs={"client_pk": client_pk})))

presentation_server/views/BlockedClientsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View
from django.views.generic.list import ListView

from common.libs import ClientManager, ClientsStateManager


class BlockedClientsView(LoginRequiredMixin, ListView):
    login_url = '/aps/login/'
    template_name = "presentation_server/BlockedClientsView.html"
    # def get(self, request, *args, **kwargs):
    #     blocked_clients = ClientManager.get_all_blocked()
    #     context = {"current_url": request.get_full_path(), "blocked_clients": blocked_clients}
    #     return render(request, 'presentation_server/BlockedClientsView.html', context)

    def get_queryset(self):
        return ClientManager.get_all_blocked()

    def post(self, request, *args, **kwargs):
        pk = request.POST.get('client_pk')

        if request.POST.get('accept'):
            ClientsStateManager.accept_blocked_client(int(pk))
            return HttpResponseRedirect(
                reverse("aps:ClientConfiguration", kwargs={"client_pk": pk}))

        return HttpResponseRedirect(request.get_full_path())

presentation_server/views/ClientConfigurationView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View

from common.libs import ClientManager, ClientsConfigurator
from presentation_server.views.forms.ClientConfigurationForm import ClientConfigurationForm
from presentation_server.views.forms.ThresholdForm import ThresholdForm


class ClientConfigurationView(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def get(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        error = kwargs['error_message']
        error_message = error if error != None else ""
        client = ClientManager.get_client(pk)
        if client is None:
            raise Http404
        return render(request, 'presentation_server/ClientConfigurationView.html',
                      self._create_context(
                          request,
                          client))

    def post(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        if request.POST.get("delete") is not None:
            if (ClientManager.remove_client_anystate(pk)):
                return HttpResponseRedirect(reverse("aps:index"))
            else:
                redirect_kwargs = {"client_pk": pk, "error_message": "client could not be deleted"}
                HttpResponseRedirect(reverse("aps:ClientConfiguration", kwargs=redirect_kwargs))
        elif request.POST.get("configure") is not None:
            client_conf = ClientConfigurationForm(request.POST)
            monitored_properties = request.POST.getlist('monitored_properties[]')
            property_for_dashboard = request.POST.get('show_on_dashboard[]')
            if client_conf.is_valid():
                redirect_kwargs = {"client_pk": pk}
                try:
                    ClientsConfigurator.apply_configuration(
                        pk,
                        client_conf.cleaned_data["hostname"],
                        client_conf.cleaned_data["consecutive_probes_sent_count"],
                        [int(m) for m in monitored_properties],
                        property_for_dashboard,
                        client_conf.get_monitoring_timespan()
                    )
                except Exception as e:
                    redirect_kwargs["error_message"] = str(e)
                    return HttpResponseRedirect(reverse("aps:ClientConfiguration", kwargs=redirect_kwargs))
                return HttpResponseRedirect(reverse("aps:ClientDetails", kwargs=redirect_kwargs))
            else:
                return render(request, 'acquisition_presentation_server/ClientConfigurationView.html',
                              self._create_context(
                                  request,
                                  ClientManager.get_client(pk),
                                  client_conf))

    def _create_context(self, request, client, client_form=None):
        monitored_properies = []
        for property in ClientManager.get_monitored_properties(client):
            monitored_properies.append(
                {
                    "pk": property.pk,
                    "name": property.name,
                    "type": property.type,
                    "checked": property.monitored,
                    "on_dashboard": property.name == client.property_on_dashboard.name if
                    client.property_on_dashboard is not None else False,
                    "thresholds": property.thresholds.all()
                }
            )

        return {
            "client_pk": client.pk,
            "current_url": request.get_full_path(),
            "form": ClientConfigurationForm.from_client(client) if client_form is None else client_form,
            "threshold_form": ThresholdForm.for_client(client.pk),
            "monitored_properties": monitored_properies
        }

presentation_server/views/ClientDetailsView.py
import json
import time

from django.http.response import Http404
from django.shortcuts import render
from django.views import View

from  common.libs import AlertManager
from common.libs import MonitoringDataManager
from common.libs import ClientManager


class ClientDetailsView(View):
    def get(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        client = ClientManager.get_client(pk)
        if client is None:
            raise Http404
        client_data, _ = MonitoringDataManager.get_client_data(client, int(time.time()) - client.monitoring_timespan)
        monitoring_data = json.dumps(client_data) \
            if client.is_configured and client_data is not None else []
        context = {
            "client": client,
            "monitoring_data": monitoring_data,
            "update_ratio_seconds": 5,
            "alerts": AlertManager.get_client_alerts(client)
        }
        return render(request, 'presentation_server/ClientDetailView.html', context)

presentation_server/views/IndexView.py
import json
import re

import time
from django.shortcuts import render
from django.views import View

from common.libs import MonitoringDataManager
from common.libs import ClientManager
from presentation_server.views.forms.FilteringForm import FilteringForm


class IndexView(View):
    def get(self, request, *args, **kwargs):
        clients = ClientManager.get_all_clients()
        return self._render_page(request, clients=clients)

    def post(self, request, *args, **kwargs):
        filtering_form = FilteringForm(request.POST)
        if filtering_form.is_valid():
            regex = filtering_form.cleaned_data["filter_regex"]
            sorting = filtering_form.cleaned_data["sorting"]
            sort_ascending = True if sorting == "h_asc" else False
            return self._render_page(request, ClientManager.get_clients(regex, sort_ascending),
                                     filtering_form)
        else:
            return self._render_page(request, ClientManager.get_all_clients(), filtering_form)

    @staticmethod
    def _render_page(request, clients, filtering_form=None):
        monitoring_data = {}
        for client in clients:
            client_data, _ = MonitoringDataManager.get_client_data(client,
                                                                   int(time.time()) - client.monitoring_timespan)
            monitoring_data[client.pk] = client_data \
                if client.is_configured and client_data is not None else []
        if filtering_form is None:
            filtering_form = FilteringForm()
        context = {
            "clients": clients,
            "monitoring_data": json.dumps(monitoring_data),
            "update_ratio_seconds": 5,
            "filtering_form": filtering_form
        }
        return render(request, 'presentation_server/index.html', context)

presentation_server/views/MultipleConfigureListView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from common.libs import ClientManager
from common.models import Client


class MultipleConfigureListView(LoginRequiredMixin, ListView):
    template_name = "presentation_server/MultipleConfigureListView.html"
    login_url = '/aps/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context["chosen_pk"] = self._chosen_pk
        except:
            pass
        return context

    def get_queryset(self):
        if "pks_to_configure[]" in self.request.GET.keys():
            pks = [int(pk) for pk in self.request.GET.getlist("pks_to_configure[]")]
            if len(pks) == 0:
                return ClientManager.get_all_clients()
            else:
                pk = pks[0]
                self._chosen_pk = pk
                return ClientManager.get_clients_with_same_properties(pk)
        else:
            return ClientManager.get_all_clients()

presentation_server/views/MultipleConfigureView.py
from django.http.response import HttpResponseRedirect, Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.base import View

from common.libs import ClientManager, ClientsConfigurator
from presentation_server.views.forms.MultipleClientConfigurationForm import MultipleClientConfigurationForm


class MultipleConfigureView(View):
    def post(self, request, *args, **kwargs):
        if request.POST.get("begin_configuration") is not None:
            pks = [int(pk) for pk in self.request.POST.getlist("pks_to_configure[]")]
            if len(pks) > 0:
                clients = list(ClientManager.get_clients_list(pks))
                context = {
                    "clients_to_configure": clients,
                    "form": MultipleClientConfigurationForm.from_client(clients[0]),
                    "monitored_properties": clients[0].monitored_properties.all()
                }
                return render(request, "presentation_server/MultipleConfigureView.html", context=context)
            else:
                return HttpResponseForbidden()
        elif request.POST.get("apply_configuration") is not None:
            configuration_form = MultipleClientConfigurationForm(request.POST)
            # TODO:Message jak zly.
            if configuration_form.is_valid():
                pks = [int(pk) for pk in request.POST.getlist("pks_to_configure[]")]
                property_for_dashboard = request.POST.get('show_on_dashboard[]')
                monitored_properties = request.POST.getlist('monitored_properties[]')
                ClientsConfigurator.configure_multiple(
                    pks,
                    configuration_form.cleaned_data["consecutive_probes_sent_count"],
                    configuration_form.get_monitoring_timespan(),
                    monitored_properties,
                    property_for_dashboard
                )
            return HttpResponseRedirect(reverse("aps:MultipleConfigureList"))
        else:
            raise Http404

presentation_server/views/PendingClientsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View
from django.views.generic.list import ListView

from common.libs import ClientsStateManager, ClientManager


class PendingClientsView(LoginRequiredMixin, ListView):
    login_url = '/aps/login/'
    template_name = "presentation_server/PendingClientsView.html"

    def get_queryset(self):
        return ClientManager.get_all_pending()

    def post(self, request, *args, **kwargs):
        try:
            pk = request.POST.get('pending_client_pk')

            if request.POST.get('block'):
                ClientsStateManager.block_pending_client(pk)

            if request.POST.get('accept'):
                ClientsStateManager.accept_pending_client(pk)
                return HttpResponseRedirect(
                    reverse("aps:ClientConfiguration", kwargs={"client_pk": pk}))

            return HttpResponseRedirect(request.get_full_path())
        except Exception:
            raise Http404

presentation_server/views/ThresholdConfigurationView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import View

from common.libs import ThresholdManager
from presentation_server.views.forms.ThresholdForm import ThresholdForm


class ThresholdConfigurationView(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def post(self, request, *args, **kwargs):
        client_pk = request.POST.get('client_pk')
        if request.POST.get('add_threshold'):
            form = ThresholdForm(request.POST)
            if form.is_valid():
                mp_pk = request.POST.get('mp_pk')
                value = form.cleaned_data['value']
                cycles = form.cleaned_data['cycles_above']
                threshold_type = form.cleaned_data['type']
                is_gt = form.cleaned_data['gt_or_lt'] == 'gt'
                message_template = form.cleaned_data['message_template']
                ThresholdManager.add_threshold(value, cycles, threshold_type, mp_pk, is_gt, message_template)

        if request.POST.get('delete_threshold'):
            threshold_pk = request.POST.get("threshold_pk")
            ThresholdManager.delete_threshold(threshold_pk)
        return HttpResponseRedirect(
            "{}#threshold_configuration".format(reverse("aps:ClientConfiguration", kwargs={"client_pk": client_pk})))

presentation_server/templates/presentation_server/BlockedClientsView.html
{% extends "presentation_server/skeletons/base_skeleton.html" %}
{% block title %}APS - Blocked Clients{% endblock %}
{% block content %}

    <div class="content">
        <h1>Blocked Clients</h1>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>
                    Client's hostname
                </th>
                <th>
                    Client's IP
                </th>
                <th>
                    Client's Monitored properties
                </th>
                <th>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for client in object_list %}
                <tr>
                    <td>
                        {{ client.hostname }}
                    </td>
                    <td>
                        {{ client.ip_address }}
                    </td>
                    <td>
                        {{ client.monitored_properties.all|join:", " }}
                    </td>
                    <td>
                        <form method="post" action="">
                            {% csrf_token %}
                            <input type="hidden" name="client_pk" value="{{ client.pk }}"/>
                            <button type="submit" class="btn btn-success" name="accept" value="accept">Accept
                            </button>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">
                        No clients yet.
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

presentation_server/templates/presentation_server/ClientDetailView.html
{% extends "presentation_server/skeletons/base_skeleton.html" %}
{% load staticfiles %}
{% block title %}APS - Client Details{% endblock %}
{% block head %}
    <script type="text/javascript" src="{% static "presentation_server/js/jquery-3.1.1.min.js" %}"></script>
    {% include 'presentation_server/utils/includes_for_charts.html' %}

    <script type="text/javascript">
        var charts = {};
        var chart_datasets = {{ monitoring_data | safe }};
        var pk_last_update = {};
        var time = chart_datasets["unix_time"];
        pk_last_update[{{ client.pk }}] = time[time.length - 1];
        var x = 1 + 2;
    </script>
{% endblock %}
{% block content %}
    <div class="content">
        <h1>Client Details - <span class="accent">{{ client.hostname }} </span>
            {{ client.ip_address }}</h1>
        <div class="content_unit">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#charts" aria-controls="charts"
                                                          role="tab" data-toggle="tab">Charts</a>
                </li>
                <li role="presentation"><a href="#alerts" aria-controls="alerts"
                                           role="tab"
                                           data-toggle="tab">Alerts</a>
                </li>
            </ul>

            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="charts">
                    <div id="client_charts"></div>
                    <script type="text/javascript">
                        $(document).ready(function () {
                            for (var data_entry in chart_datasets["data"]) {
                                var data_json = chart_datasets["data"][data_entry];
                                var element = document.createElement("div");
                                element.setAttribute("id", data_entry);
                                document.getElementById("client_charts").appendChild(element);
                                charts[data_entry] = create_chart("#" + data_entry,
                                        data_json,
                                        chart_datasets["unix_time"],
                                        data_entry,
                                        "unit"
                                );
                            }
                        })
                    </script>
                    <div>
                        {% if user.is_authenticated %}
                            <form method="get" action="{% url 'aps:ClientConfiguration' client.pk "" %}">
                                <button type="submit" value="configure"
                                        class="btn btn-warning">Configure
                                </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div role="tabpanel" class="tab-pane" id="alerts">
                    <div>
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Alert message</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for alert in alerts %}
                                <tr>
                                    <th>
                                        {{ forloop.counter }}
                                    </th>
                                    <td>
                                        {{ alert.message }}
                                    </td>
                                    <td>
                                        <form method="post" action="{% url 'aps:AlertsCleaner' client.pk %}">
                                            {% csrf_token %}
                                            <input type="hidden" name="alert_pk" value="{{ alert.pk }}"/>
                                            <button type="submit" value="delete_single" name="delete_single"
                                                    class="btn btn-sm"><span class="glyphicon glyphicon-minus"/>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div>
                        {% if user.is_authenticated %}
                            <form method="post" action="{% url 'aps:AlertsCleaner' client.pk %}">
                                {% csrf_token %}
                                <button type="submit" value="delete_all" name="delete_all"
                                        class="btn btn-danger">Delete all
                                </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function updateCharts() {
            var to_send = JSON.stringify(pk_last_update);
            $.ajax({
                url: "{% url 'aps:UpdateCharts' %}", // the endpoint
                type: "POST", // http method
                data: {
                    pk_last_update: to_send
                }, // data sent with the post request

                // handle a successful response
                success: function (json) {
                    var monitoring_data = json["monitoring_data"][{{ client.pk}}];
                    pk_last_update = json["pk_last_update"];
                    for (var data_entry in monitoring_data["data"]) {
                        var chart = charts[data_entry];
                        update_chart(chart,
                                monitoring_data["data"][data_entry],
                                monitoring_data["unix_time"]
                        );
                    }
                },

                // handle a non-successful response
                error: function (xhr, errmsg, err) {
                    $('#results').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: " + errmsg +
                            " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                    console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
                }
            });
        }
        $(document).ready(function () {
            setInterval(updateCharts, ({{ update_ratio_seconds }}) * 1000);
        });
        $(function () {
            var hash = document.location.hash;
            if (hash) {
                $('.nav-tabs a[href=\'' + hash + '\']').tab('show');
            }
            $('a[data-toggle="tab"]').on('show.bs.tab', function (e) {
                window.location.hash = e.target.hash;
            });
        });
    </script>
{% endblock %}

presentation_server/templates/presentation_server/MultipleConfigureListView.html
{% extends "presentation_server/skeletons/base_skeleton.html" %}
{% block title %}APS - Multiple Client Configuration{% endblock %}
{% block content %}
    <div class="content">
        <form method="get" action="">
            {% csrf_token %}
            <h1>Multiple Client Configuration</h1>
            <button id="ConfigureSelectedButton"
                    class="btn btn-success" type="submit"
                    formaction="{% url "aps:MultipleConfigure"%}"
                    formmethod="post"
                    name="begin_configuration"
            >Configure Selected</button>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>
                        Client's hostname
                    </th>
                    <th>
                        Client's IP
                    </th>
                    <th>
                        Client's Monitored properties
                    </th>
                    <th>
                        Configure
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for client in object_list %}
                    <tr>
                        <td>
                            {{ client.hostname }}
                        </td>
                        <td>
                            {{ client.ip_address }}
                        </td>
                        <td>
                            {{ client.monitored_properties.all|join:", " }}
                        </td>
                        <td>
                            <input title="Add client to configured set!" type="checkbox"
                            name="pks_to_configure[]" value="{{ client.pk }}"
                                   onchange="checkbox_manipulation(this)"
                            {% if client.pk == chosen_pk %}checked{% endif %}>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4">
                            No clients yet.
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        <script type="text/javascript">
            function checkbox_manipulation(checkbox) {
                var selected_count = document.querySelectorAll(
                        'input[name="pks_to_configure[]"]:checked').length;
                if(checkbox.checked && selected_count==1 ||
                        !checkbox.checked && selected_count==0) {
                    //alert("Aktualnie " + selected_count + "Zaznaczone!");
                    checkbox.form.submit()
                }

            }
        </script>
        </form>
    </div>
{% endblock %}

presentation_server/templates/presentation_server/PendingClientsView.html
{% extends "presentation_server/skeletons/base_skeleton.html" %}
{% block title %}APS - Pending Clients{% endblock %}
{% block content %}
    <div class="content">
        <h1>Pending Clients</h1>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>
                    Client's hostname
                </th>
                <th>
                    Client's IP
                </th>
                <th>
                    Client's Monitored properties
                </th>
                <th>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for client in object_list %}
                <tr>
                    <td>
                        {{ client.hostname }}
                    </td>
                    <td>
                        {{ client.ip_address }}
                    </td>
                    <td>
                        {{ client.monitored_properties.all|join:", " }}
                    </td>
                    <td>
                        <form method="post" action="">
                            {% csrf_token %}
                            <input type="hidden" name="pending_client_pk" value="{{ client.pk }}"/>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-success" name="accept" value="accept">Accept
                                </button>
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-danger" name="block" value="block">Block
                                </button>
                            </div>
                        </form>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">
                        No new pending clients.
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}