APS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^aps_client/', include("acquisition_server.urls")),
    url(r'^aps/', include("presentation_server.urls")),
]

presentation_server/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from presentation_server.views.AlertsCleaner import AlertsCleaner
from presentation_server.views.BlockedClientsView import BlockedClientsView
from presentation_server.views.ClientConfigurationView import ClientConfigurationView
from presentation_server.views.ClientDetailsView import ClientDetailsView
from presentation_server.views.MultipleConfigureView import MultipleConfigureView
from presentation_server.views.IndexView import IndexView
from presentation_server.views.MultipleConfigureListView import MultipleConfigureListView
from presentation_server.views.PendingClientsView import PendingClientsView
from presentation_server.views.ThresholdConfigurationView import ThresholdConfigurationView
from presentation_server.views.UpdateCharts import UpdateCharts

app_name = 'aps'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^ClientConfiguration/(?P<client_pk>[0-9]+)/(?P<error_message>.*)?$',
        ClientConfigurationView.as_view(), name='ClientConfiguration'),
    url(r'^ClientDetails/(?P<client_pk>[0-9]+)$',
        ClientDetailsView.as_view(), name='ClientDetails'),
    url(r'^PendingClients/$', PendingClientsView.as_view(), name='PendingClients'),
    url(r'^BlockedClients/$', BlockedClientsView.as_view(), name='BlockedClients'),
    url(r'^UpdateCharts/$', UpdateCharts.as_view(),
        name='UpdateCharts'),
    url(r'^login/', auth_views.login,
        {
            'template_name': "presentation_server/auth/login.html",
        },
        name="login",
        ),
    url(r'^logout/', auth_views.logout,
        {
            'next_page': "/aps/",
        },
        name="logout",
        ),
    url(r'^ThresholdConfiguration$',
        ThresholdConfigurationView.as_view(), name='ThresholdConfiguration'),
    url(r'^AlertsCleaner/(?P<client_pk>[0-9]+)$',
        AlertsCleaner.as_view(), name='AlertsCleaner'),
    url(r'^MultipleConfigureList',
        MultipleConfigureListView.as_view(), name='MultipleConfigureList'),
    url(r'^MultipleConfigure',
        MultipleConfigureView.as_view(), name='MultipleConfigure'),

]

presentation_server/views/AlertsCleaner.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import View

from common.libs import AlertManager


class AlertsCleaner(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def post(self, request, *args, **kwargs):
        client_pk = kwargs["client_pk"]
        if request.POST.get('delete_single'):
            AlertManager.delete_alert(int(request.POST.get("alert_pk")))
        if request.POST.get('delete_all'):
            AlertManager.delete_all_for_client(client_pk)
        return HttpResponseRedirect(
            "{}#alerts".format(reverse("aps:ClientDetails", kwargs={"client_pk": client_pk})))

presentation_server/views/BlockedClientsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View
from django.views.generic.list import ListView

from common.libs import ClientManager, ClientsStateManager


class BlockedClientsView(LoginRequiredMixin, ListView):
    login_url = '/aps/login/'
    template_name = "presentation_server/BlockedClientsView.html"
    # def get(self, request, *args, **kwargs):
    #     blocked_clients = ClientManager.get_all_blocked()
    #     context = {"current_url": request.get_full_path(), "blocked_clients": blocked_clients}
    #     return render(request, 'presentation_server/BlockedClientsView.html', context)

    def get_queryset(self):
        return ClientManager.get_all_blocked()

    def post(self, request, *args, **kwargs):
        pk = request.POST.get('client_pk')

        if request.POST.get('accept'):
            ClientsStateManager.accept_blocked_client(int(pk))
            return HttpResponseRedirect(
                reverse("aps:ClientConfiguration", kwargs={"client_pk": pk}))

        return HttpResponseRedirect(request.get_full_path())

presentation_server/views/ClientConfigurationView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View

from common.libs import ClientManager, ClientsConfigurator
from presentation_server.views.forms.ClientConfigurationForm import ClientConfigurationForm
from presentation_server.views.forms.ThresholdForm import ThresholdForm


class ClientConfigurationView(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def get(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        error = kwargs['error_message']
        error_message = error if error != None else ""
        client = ClientManager.get_client(pk)
        if client is None:
            raise Http404
        return render(request, 'presentation_server/ClientConfigurationView.html',
                      self._create_context(
                          request,
                          client))

    def post(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        if request.POST.get("delete") is not None:
            if (ClientManager.remove_client_anystate(pk)):
                return HttpResponseRedirect(reverse("aps:index"))
            else:
                redirect_kwargs = {"client_pk": pk, "error_message": "client could not be deleted"}
                HttpResponseRedirect(reverse("aps:ClientConfiguration", kwargs=redirect_kwargs))
        elif request.POST.get("configure") is not None:
            client_conf = ClientConfigurationForm(request.POST)
            monitored_properties = request.POST.getlist('monitored_properties[]')
            property_for_dashboard = request.POST.get('show_on_dashboard[]')
            if client_conf.is_valid():
                redirect_kwargs = {"client_pk": pk}
                try:
                    ClientsConfigurator.apply_configuration(
                        pk,
                        client_conf.cleaned_data["hostname"],
                        client_conf.cleaned_data["consecutive_probes_sent_count"],
                        [int(m) for m in monitored_properties],
                        property_for_dashboard,
                        client_conf.get_monitoring_timespan()
                    )
                except Exception as e:
                    redirect_kwargs["error_message"] = str(e)
                    return HttpResponseRedirect(reverse("aps:ClientConfiguration", kwargs=redirect_kwargs))
                return HttpResponseRedirect(reverse("aps:ClientDetails", kwargs=redirect_kwargs))
            else:
                return render(request, 'acquisition_presentation_server/ClientConfigurationView.html',
                              self._create_context(
                                  request,
                                  ClientManager.get_client(pk),
                                  client_conf))

    def _create_context(self, request, client, client_form=None):
        monitored_properies = []
        for property in ClientManager.get_monitored_properties(client):
            monitored_properies.append(
                {
                    "pk": property.pk,
                    "name": property.name,
                    "type": property.type,
                    "checked": property.monitored,
                    "on_dashboard": property.name == client.property_on_dashboard.name if
                    client.property_on_dashboard is not None else False,
                    "thresholds": property.thresholds.all()
                }
            )

        return {
            "client_pk": client.pk,
            "current_url": request.get_full_path(),
            "form": ClientConfigurationForm.from_client(client) if client_form is None else client_form,
            "threshold_form": ThresholdForm.for_client(client.pk),
            "monitored_properties": monitored_properies
        }

presentation_server/views/ClientDetailsView.py
import json
import time

from django.http.response import Http404
from django.shortcuts import render
from django.views import View

from  common.libs import AlertManager
from common.libs import MonitoringDataManager
from common.libs import ClientManager


class ClientDetailsView(View):
    def get(self, request, *args, **kwargs):
        pk = kwargs['client_pk']
        client = ClientManager.get_client(pk)
        if client is None:
            raise Http404
        client_data, _ = MonitoringDataManager.get_client_data(client, int(time.time()) - client.monitoring_timespan)
        monitoring_data = json.dumps(client_data) \
            if client.is_configured and client_data is not None else []
        context = {
            "client": client,
            "monitoring_data": monitoring_data,
            "update_ratio_seconds": 5,
            "alerts": AlertManager.get_client_alerts(client)
        }
        return render(request, 'presentation_server/ClientDetailView.html', context)

presentation_server/views/IndexView.py
import json
import re

import time
from django.shortcuts import render
from django.views import View

from common.libs import MonitoringDataManager
from common.libs import ClientManager
from presentation_server.views.forms.FilteringForm import FilteringForm


class IndexView(View):
    def get(self, request, *args, **kwargs):
        clients = ClientManager.get_all_clients()
        return self._render_page(request, clients=clients)

    def post(self, request, *args, **kwargs):
        filtering_form = FilteringForm(request.POST)
        if filtering_form.is_valid():
            regex = filtering_form.cleaned_data["filter_regex"]
            sorting = filtering_form.cleaned_data["sorting"]
            sort_ascending = True if sorting == "h_asc" else False
            return self._render_page(request, ClientManager.get_clients(regex, sort_ascending),
                                     filtering_form)
        else:
            return self._render_page(request, ClientManager.get_all_clients(), filtering_form)

    @staticmethod
    def _render_page(request, clients, filtering_form=None):
        monitoring_data = {}
        for client in clients:
            client_data, _ = MonitoringDataManager.get_client_data(client,
                                                                   int(time.time()) - client.monitoring_timespan)
            monitoring_data[client.pk] = client_data \
                if client.is_configured and client_data is not None else []
        if filtering_form is None:
            filtering_form = FilteringForm()
        context = {
            "clients": clients,
            "monitoring_data": json.dumps(monitoring_data),
            "update_ratio_seconds": 5,
            "filtering_form": filtering_form
        }
        return render(request, 'presentation_server/index.html', context)

presentation_server/views/MultipleConfigureListView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView

from common.libs import ClientManager
from common.models import Client


class MultipleConfigureListView(LoginRequiredMixin, ListView):
    template_name = "presentation_server/MultipleConfigureListView.html"
    login_url = '/aps/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            context["chosen_pk"] = self._chosen_pk
        except:
            pass
        return context

    def get_queryset(self):
        if "pks_to_configure[]" in self.request.GET.keys():
            pks = [int(pk) for pk in self.request.GET.getlist("pks_to_configure[]")]
            if len(pks) == 0:
                return ClientManager.get_all_clients()
            else:
                pk = pks[0]
                self._chosen_pk = pk
                return ClientManager.get_clients_with_same_properties(pk)
        else:
            return ClientManager.get_all_clients()

presentation_server/views/MultipleConfigureView.py
from django.http.response import HttpResponseRedirect, Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls.base import reverse
from django.views.generic.base import View

from common.libs import ClientManager, ClientsConfigurator
from presentation_server.views.forms.MultipleClientConfigurationForm import MultipleClientConfigurationForm


class MultipleConfigureView(View):
    def post(self, request, *args, **kwargs):
        if request.POST.get("begin_configuration") is not None:
            pks = [int(pk) for pk in self.request.POST.getlist("pks_to_configure[]")]
            if len(pks) > 0:
                clients = list(ClientManager.get_clients_list(pks))
                context = {
                    "clients_to_configure": clients,
                    "form": MultipleClientConfigurationForm.from_client(clients[0]),
                    "monitored_properties": clients[0].monitored_properties.all()
                }
                return render(request, "presentation_server/MultipleConfigureView.html", context=context)
            else:
                return HttpResponseForbidden()
        elif request.POST.get("apply_configuration") is not None:
            configuration_form = MultipleClientConfigurationForm(request.POST)
            # TODO:Message jak zly.
            if configuration_form.is_valid():
                pks = [int(pk) for pk in request.POST.getlist("pks_to_configure[]")]
                property_for_dashboard = request.POST.get('show_on_dashboard[]')
                monitored_properties = request.POST.getlist('monitored_properties[]')
                ClientsConfigurator.configure_multiple(
                    pks,
                    configuration_form.cleaned_data["consecutive_probes_sent_count"],
                    configuration_form.get_monitoring_timespan(),
                    monitored_properties,
                    property_for_dashboard
                )
            return HttpResponseRedirect(reverse("aps:MultipleConfigureList"))
        else:
            raise Http404

presentation_server/views/PendingClientsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls.base import reverse
from django.views import View
from django.views.generic.list import ListView

from common.libs import ClientsStateManager, ClientManager


class PendingClientsView(LoginRequiredMixin, ListView):
    login_url = '/aps/login/'
    template_name = "presentation_server/PendingClientsView.html"

    def get_queryset(self):
        return ClientManager.get_all_pending()

    def post(self, request, *args, **kwargs):
        try:
            pk = request.POST.get('pending_client_pk')

            if request.POST.get('block'):
                ClientsStateManager.block_pending_client(pk)

            if request.POST.get('accept'):
                ClientsStateManager.accept_pending_client(pk)
                return HttpResponseRedirect(
                    reverse("aps:ClientConfiguration", kwargs={"client_pk": pk}))

            return HttpResponseRedirect(request.get_full_path())
        except Exception:
            raise Http404

presentation_server/views/ThresholdConfigurationView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect
from django.urls.base import reverse
from django.views import View

from common.libs import ThresholdManager
from presentation_server.views.forms.ThresholdForm import ThresholdForm


class ThresholdConfigurationView(LoginRequiredMixin, View):
    login_url = '/aps/login/'

    def post(self, request, *args, **kwargs):
        client_pk = request.POST.get('client_pk')
        if request.POST.get('add_threshold'):
            form = ThresholdForm(request.POST)
            if form.is_valid():
                mp_pk = request.POST.get('mp_pk')
                value = form.cleaned_data['value']
                cycles = form.cleaned_data['cycles_above']
                threshold_type = form.cleaned_data['type']
                is_gt = form.cleaned_data['gt_or_lt'] == 'gt'
                message_template = form.cleaned_data['message_template']
                ThresholdManager.add_threshold(value, cycles, threshold_type, mp_pk, is_gt, message_template)

        if request.POST.get('delete_threshold'):
            threshold_pk = request.POST.get("threshold_pk")
            ThresholdManager.delete_threshold(threshold_pk)
        return HttpResponseRedirect(
            "{}#threshold_configuration".format(reverse("aps:ClientConfiguration", kwargs={"client_pk": client_pk})))

presentation_server/templates/presentation_server/skeletons/base_skeleton.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'presentation_server/images/favicon.ico' %}">

    <title>{% block title %}Acquisition Presentation Server{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static  'presentation_server/css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "presentation_server/js/jquery-3.1.1.min.js" %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static  'presentation_server/assets/css/ie10-viewport-bug-workaround.css' %}"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "presentation_server/css/dashboard.css" %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static "presentation_server/assets/js/ie-emulation-modes-warning.js" %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block head %}{% endblock %}
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand" >APS</span>
            <ul class="nav navbar-nav navbar-left">
                <li><a class="white_big" href="{% url 'aps:index' %}">Clients</a></li>
                {% if user.is_authenticated %}
                    <li><a class="white_big" href="{% url 'aps:PendingClients' %}">Pending Clients </a>
                    </li>
                    <li><a class="white_big" href="{% url 'aps:BlockedClients' %}">Blocked Clients </a>
                    </li>
                    <li><a class="white_big" href="{% url 'aps:MultipleConfigureList' %}">Multiple Clients Configuration</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a class="white_big" href="{% url "aps:logout" %}">Logout</a></li>
                {% else %}
                    <li><a class="white_big" href="{% url "aps:login" %}?next={% url "aps:index" %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">
        {% block content %}{% endblock %}
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="{% static "presentation_server/js/bootstrap.min.js" %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static "presentation_server/assets/js/vendor/holder.min.js" %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static "presentation_server/assets/js/ie10-viewport-bug-workaround.js" %}"></script>
</body>
</html>